### ISSUE TITLE
Unable to connect to server when using SSL

### ISSUE THREAD

**Issue by fabbione** [mesacarlos/WebConsole#65] opened 2021-02-27 05:58 UTC
Hi Carlos,

I have been trying to setup WebConsole-2.1 on a spigot 1.16.5, on Centos 8 stream server.

As long as I don´t use SSL, everything works like a champ and thanks for that. My son is very happy about it :)

I have enabled SSL with let´s encrypt certificates, following your guide to convert the certificate to keystore. So far it´s all good. I can see with different clients that the certificates are valid (both pure https and accessing https://server:port/.

Tho, when I access https://server:port/ I get: "404 WebSocket Upgrade Failure" that seems to be triggered by org/java_websocket/WebSocketImpl.class (only file that matches that specific error) and clearly Client.zip refuses to connect to it.

Firewall is setup correctly (it works in http and i can see connections going via tcpdump, both server side and client side).

There are no errors generated by running the spigot server.

[06:51:20] [WebSocketSelector-57/INFO]: [WebConsole] WebSocket Server started successfully.

So I am a bit lost here.. my config is simple:

$ cat config.yml
useSSL: true
StoreType: JKS
KeyStore: plugins/WebConsole/keystore.jks
StorePassword: redactedpasswd
KeyPassword: redactedpasswd
host: 0.0.0.0
port: 25575
language: en
passwords:
  admin:
[snip]

google search was not very useful to me, I am a total newbie in java.

I would appreciate any help that you could give. Using http is not exactly what I had in mind :)

Thanks
Fabio

**Comment by fabbione** [comment] 2021-02-27 06:05
as a side note, I noticed similar bugs already reported in github about this specific error message. I understand that accessing the  https://server:port/ will return this 404 error. Tho the client simply refuses to connect to the server when SSL is enabled.

sorry if there is a known solution, I am just too fresh for java debugging.. :)

**Comment by fabbione** [comment] 2021-02-27 06:12
FYI Also verified with gnutls-cli that the certificates offered by Websockets are valid and correct.

**Comment by fabbione** [comment] 2021-02-27 06:15
tested also with different browsers (firefox, chrome, edge). Client refuses to connect to server. They all report valid SSL certs :)

**Comment by fabbione** [comment] 2021-02-27 06:30
One last thing, following the README here: https://github.com/TooTallNate/Java-WebSocket about wss:

"The vm option -Djavax.net.debug=all can help to find out if there is a problem with the certificate."

I added the option and when the client attempts to connect to the server I get the following error:

[07:25:44] [WebSocketSelector-55/WARN]: javax.net.ssl|DEBUG|37|WebSocketSelector-55|2021-02-27 07:25:44.746 CET|Alert.java:238|Received alert message (
[07:25:44] [WebSocketSelector-55/WARN]: "Alert": {
[07:25:44] [WebSocketSelector-55/WARN]:   "level"      : "fatal",
[07:25:44] [WebSocketSelector-55/WARN]:   "description": "bad_certificate"
[07:25:44] [WebSocketSelector-55/WARN]: }
[07:25:44] [WebSocketSelector-55/WARN]: )
[07:25:44] [WebSocketSelector-55/WARN]: javax.net.ssl|ERROR|37|WebSocketSelector-55|2021-02-27 07:25:44.747 CET|TransportContext.java:342|Fatal (BAD_CERTIFICATE): Received fatal alert: bad_certificate (
[07:25:44] [WebSocketSelector-55/WARN]: "throwable" : {
[07:25:44] [WebSocketSelector-55/WARN]:   javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:337)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:186)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
[07:25:44] [WebSocketSelector-55/WARN]:         at org.java_websocket.SSLSocketChannel2.unwrap(SSLSocketChannel2.java:203)
[07:25:44] [WebSocketSelector-55/WARN]:         at org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:163)
[07:25:44] [WebSocketSelector-55/WARN]:         at org.java_websocket.SSLSocketChannel2.write(SSLSocketChannel2.java:251)
[07:25:44] [WebSocketSelector-55/WARN]:         at org.java_websocket.SSLSocketChannel2.writeMore(SSLSocketChannel2.java:397)
[07:25:44] [WebSocketSelector-55/WARN]:         at org.java_websocket.SocketChannelIOHelper.batch(SocketChannelIOHelper.java:89)
[07:25:44] [WebSocketSelector-55/WARN]:         at org.java_websocket.server.WebSocketServer.doWrite(WebSocketServer.java:511)
[07:25:44] [WebSocketSelector-55/WARN]:         at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:377)
[07:25:44] [WebSocketSelector-55/WARN]:         at es.mesacarlos.webconsole.WebConsole$1.run(WebConsole.java:94)
[07:25:44] [WebSocketSelector-55/WARN]:         at java.base/java.lang.Thread.run(Thread.java:834)}
[07:25:44] [WebSocketSelector-55/WARN]:
[07:25:44] [WebSocketSelector-55/WARN]: )
[07:25:44] [WebSocketSelector-55/WARN]: javax.net.ssl|ALL|37|WebSocketSelector-55|2021-02-27 07:25:44.747 CET|SSLSessionImpl.java:784|Invalidated session:  Session(1614407144672|SSL_NULL_WITH_NULL_NULL)
[07:25:44] [WebSocketSelector-55/WARN]: javax.net.ssl|ALL|37|WebSocketSelector-55|2021-02-27 07:25:44.747 CET|SSLSessionImpl.java:784|Invalidated session:  Session(1614407144680|TLS_AES_128_GCM_SHA256)

**Comment by mesacarlos** [comment] 2021-02-27 10:05
Hi,

> as a side note, I noticed similar bugs already reported in github about this specific error message. I understand that accessing the https://server:port/ will return this 404 error. Tho the client simply refuses to connect to the server when SSL is enabled.
> 
> sorry if there is a known solution, I am just too fresh for java debugging.. :)

That's correct! Accessing https://server:port/ will return you a 404 WebSocket Upgrade Failure when your browser is able to connect to your WebConsole correctly.

----------
Does the developer console in your browser (Opened by pressing F12) shows any error when using the client?
When you browse to https://server:port/, do your browser consider the certificate as valid (["Valid certificate" when opening this dialog](https://i.imgur.com/jx8cuoM.png))?

**Comment by fabbione** [comment] 2021-02-27 10:48
> Does the developer console in your browser shows any error when using the client?

Do you prefer the output from a specific browser?

> When you browse to https://server:port/, do your browser consider the certificate as valid (["Valid certificate" when opening this dialog](https://i.imgur.com/jx8cuoM.png))?

Yes the certificates are valid. Tested from many different clients.

> 
> Edit: Just in case, please try creating again the keystore.jks (Just in case the password was not set correctly... Just happened to me, I typed it incorrectly when creating the keystore 🤣)

Already did this too, and even double tested with a bad password on purpose. You get a specific error loading Webconsole if the password is wrong. Loading is fine.

Fabio

**Comment by mesacarlos** [comment] 2021-02-27 11:06
> Do you prefer the output from a specific browser?

The one you like the most is fine.

**Comment by fabbione** [comment] 2021-02-27 12:43
I can´t see anything, but you can double check as well, I am too much of a newbie debugging "web stuff":

https://leinad211.fugedabout.it:25575/

**Comment by mesacarlos** [comment] 2021-02-27 17:19
Hi,

On my side, everything seems to work as expected:

![image](https://i.imgur.com/zXpsQoZ.png)



Maybe some extension on your browser is blocking SSL WebConsole connections, or something related.

**Comment by fabbione** [comment] 2021-02-27 21:15
@mesacarlos what browser or client are you using?

I have tired chrome /firefox / edge, cleared the cookies, both locally installed client and your https://mesacarlos.es/webconsole/

I don´t use any extensions in chrome or edge and I know network connectivity is good (otherwise http wouldn´t work either)

**Comment by mesacarlos** [comment] 2021-02-27 21:21
> @mesacarlos what browser or client are you using?
> 
> I have tired chrome /firefox / edge, cleared the cookies, both locally installed client and your https://mesacarlos.es/webconsole/
> 
> I don´t use any extensions in chrome or edge and I know network connectivity is good (otherwise http wouldn´t work either)

I'm using Chrome (latest version), Windows 10 and WebConsole 2.1 from my webpage.
Maybe you are using some proxy or VPN?

**Comment by fabbione** [comment] 2021-02-27 21:25
> 
> 
> > @mesacarlos what browser or client are you using?
> > I have tired chrome /firefox / edge, cleared the cookies, both locally installed client and your https://mesacarlos.es/webconsole/
> > I don´t use any extensions in chrome or edge and I know network connectivity is good (otherwise http wouldn´t work either)
> 
> I'm using Chrome (latest version), Windows 10 and WebConsole 2.1 from my webpage.

I have tried this combination as well.

> Maybe you are using some proxy or VPN?

I have direct connection, no proxy or VPN. tho I will investigate some more since it´s working for you.

Thanks so far!

Fabio

**Comment by fabbione** [comment] 2021-02-27 21:39
Tested again with firewall down, using another internet provider (from the phone).. same error. This is really weird (and rather annoying too ;))

Yes SSL is set to yes in the  Client. The Client is running on htts:// web server (and also tested from your Client.

**Comment by mesacarlos** [comment] 2021-02-27 21:52
Hello,

Let's try something different:
Try using https://www.browserling.com/ In that webpage, they give without registration and for free for 3 minutes a virtual machine with the internet browser specified by you to test webpages or just try a service.

Try accessing from there to, for example, my hosted clients, and try to connect from there. I just tested it, and it works as expected. I'm prompted for password.

**Comment by fabbione** [comment] 2021-02-28 04:34
ahahah omg.. i just figured it out.

If you use the server IP (138.x.y.z) it doesn´t work. if you use the host name it does. This seems like an issue in matching the certificate with the FQDN. The reverse DNS for my server is correct. it matches the FQDN

I was mislead by "Server IP" as "Use 123.x.y.z".

Tho to avoid this issue I would probably do:

- Change "Server IP" to "Server hostname or IP"
- If the user adds an pure IP address (IPv4 or IPv6) warn the user to use the FQDN as certificate verification could fail
- if the user continues with the IP, then try to connect, if it fails attempt a reverse DNS lookup and if you get a full domain name, try to use it before returning an error.

make sense?

and thanks again for all this help Carlos.

Muchas gracias

**Comment by fabbione** [comment] 2021-02-28 05:08
One unrelated question to the problem..

how does Webconsole handles SSL certs renewal? I have the usual automated settings for let´s encrypt to renew server certs, I can easily extend that script to write a new keystore. Does Webconsole re-read the keystore from time to time or do I have to restart the server? If not, can we potentially extend the plugin to:
- reread the keystore if the file change (for example by checking the timestamp) <- this would be ideal when using same passwords
- add a manual call /webconsole reload-keystore

the use case is:
- admin have automatic renewal of certificates enabled
- keystore needs to be updated
- being able to automate the keystore renewal would be nice

if server restart is required, then there are plugins such as https://www.spigotmc.org/resources/1-8-1-16-2k-users-ultimateautorestart-need-an-autorestart-plugin-grab-the-best-one-today.64414/updates to do that.

make sense?

**Comment by mesacarlos** [comment] 2021-02-28 11:01
Hi!

Glad to hear that the issue is solved!

I'm closing this issue but I'll take your suggestions for the next WebConsole updates.

Thank you!

**Closed by mesacarlos** 2021-02-28 11:01 UTC

**Comment by fabbione** [comment] 2021-02-28 11:53
> 
> 
> Hi!
> 
> Glad to hear that the issue is solved!

can you reproduce the problem with one of your servers?

If we want to be super pedantic, the issue itself "accessing Webconsole via SSL with IP address" is not solved, there is a workaround using the FQDN.

> 
> I'm closing this issue but I'll take your suggestions for the next WebConsole updates.

thanks appreciated.

> 
> Thank you!

do you have any answer about the certificate renewal process? or at the moment we just need to restart the server?

**Comment by mesacarlos** [comment] 2021-02-28 12:33
> can you reproduce the problem with one of your servers?
> 
> If we want to be super pedantic, the issue itself "accessing Webconsole via SSL with IP address" is not solved, there is a workaround using the FQDN.

Yes, I'm able to reproduce the issue, but is not a problem with WebConsole. The problem is that Let's encrypt certificates are only valid for domain names, not for IP addresses. You can check this installing your certificate on a Apache or any HTTP server, and you will notice that, if you try to connect to it over HTTPS using your IP address, your browser will warn you that the certificate is not valid and will not connect. 

> do you have any answer about the certificate renewal process? or at the moment we just need to restart the server?

At this moment, the only solution would be, as you said, to reload the plugin when keystore changes.

**Comment by fabbione** [comment] 2021-02-28 12:38
thanks for the clarifications!

Fabio
