### ISSUE TITLE
TPS not working

### ISSUE THREAD

**Issue by Felendo** [mesacarlos/WebConsole#131] opened 2023-02-27 23:23 UTC
Everything else is working fine exept the TPS Display. It says 0/20 as shown in the Image below, but my TPS is 100% between 19-20...
https://imgur.com/a/s4sndtn

**Comment by mesacarlos** [comment] 2023-02-28 05:45
#108 
Are you on Spigot or paper? Which MC version?

**Comment by OwenWasHer** [comment] 2023-03-06 08:25
I'm having the same issue. Currently on Purpur 1.19.2.

**Comment by mesacarlos** [comment] 2023-06-02 18:29
Closing as duplicate of #108

**Closed by mesacarlos** 2023-06-02 18:29 UTC
