### ISSUE TITLE
Connected and waiting login from / (ip)

### ISSUE THREAD

**Issue by shapti** [mesacarlos/WebConsole#67] opened 2021-03-15 13:35 UTC
Every time I connect using the right open port with the right IP I get the same error. I tried re-installing the plugin and even after not even touching the config.yml file I still could not join. I need this plugin as I cannot type in the console from my raspberry pi 4. I had it working a few months ago, but after a memory wipe the plugin keeps giving this error. Any help would be much appreciated!!

**Comment by mesacarlos** [comment] 2021-03-15 19:02
And the client doesn't prompt you to type your password?

**Comment by shapti** [comment] 2021-03-17 07:05
It does prompt me to type the password, but after I type in the IP and port and hit save & connect the console shows "[WebConsole] Connected and waiting login from / (IP). The password adds nothing and when I type any password (no matter if it's the right or wrong password), nothing happens. I don't get any error I just see an empty console. My console on the pi 4 doesn't say anything either.

**Comment by mesacarlos** [comment] 2021-03-17 17:18
Strange...
What browser are you using?

**Comment by shapti** [comment] 2021-03-17 22:33
I am using chrome

**Comment by mesacarlos** [comment] 2021-03-18 18:36
Does your browser console reports something?
You can open the browser console by pressing F12.
Try to type your password and check if any error appears in the browser console.

**Comment by shapti** [comment] 2021-03-20 09:46
After filling in the password, only one error appears:

WebConsoleLanguage.js?v=2.2:513 Cannot translate noServersAdded (No servers added)

**Comment by shapti** [comment] 2021-03-20 09:49
After filling in the password, this is the last thing that happens when pressing f12:

<div class="modal fade" id="passwordModal" tabindex="-1" role="dialog" aria-labelledby="passwordModalCenterTitle" style="display: none;" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="passwordModalLongTitle">Password required</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">×</span>
						</button>
					</div>
					<div class="modal-body">
						<form id="passwordForm">
							<div class="form-group">
								<label for="server-pwd" class="col-form-label" id="passwordModalLabel">Password:</label>
								<input type="password" class="form-control" id="server-pwd">
							</div>
							<div class="form-group">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="rememberPwdCheckbox">
									<label class="form-check-label" for="rememberPwdCheckbox" id="passwordModalRememberLabel">Remember password</label>
								</div>
							</div>
						</form>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal" id="passwordModalCloseButton">Close</button>
						<button type="button" class="btn btn-primary" data-dismiss="modal" id="passwordSendButton">Login</button>
					</div>
				</div>
			</div>
		</div>

**Comment by mesacarlos** [comment] 2021-03-20 12:40
That error is normal, no problems with it.

Do you have any browser extension, proxy or VPN that could be interfering with the connection?

**Comment by shapti** [comment] 2021-03-22 11:38
I had a vpn app which I was not using, uninstalled it and restarted my laptop. Still not working.

**Comment by mesacarlos** [comment] 2021-04-03 16:54
Hello,

I'm not able to reproduce this issue, sorry. Closing this issue as irreproducible.

**Closed by mesacarlos** 2021-04-03 16:54 UTC
